# Generated by Django 6.1 on 2026-08-10 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('admin', models.CharField(max_length=42)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('constitution', models.TextField()),
                ('appeal_window_seconds', models.IntegerField()),
                ('min_reputation_to_post', models.IntegerField()),
                ('starting_reputation', models.IntegerField()),
                ('reputation_penalty_violation', models.IntegerField()),
                ('reputation_penalty_bad_flag', models.IntegerField()),
                ('flag_cooldown_seconds', models.IntegerField()),
                ('created_at', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_community_id_synced', models.IntegerField(default=-1)),
                ('last_post_id_synced', models.IntegerField(default=-1)),
                ('last_comment_id_synced', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=42)),
                ('content', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('flag_count', models.IntegerField(default=0)),
                ('moderation_verdict', models.TextField(blank=True, null=True)),
                ('appeal_used', models.BooleanField(default=False)),
                ('appeal_verdict', models.TextField(blank=True, null=True)),
                ('appeal_deadline', models.IntegerField(default=0)),
                ('created_at', models.IntegerField()),
                ('flagged_at', models.IntegerField(default=0)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.community')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=42)),
                ('content', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('flag_count', models.IntegerField(default=0)),
                ('moderation_verdict', models.TextField(blank=True, null=True)),
                ('appeal_used', models.BooleanField(default=False)),
                ('appeal_verdict', models.TextField(blank=True, null=True)),
                ('appeal_deadline', models.IntegerField(default=0)),
                ('created_at', models.IntegerField()),
                ('flagged_at', models.IntegerField(default=0)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.community')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.post')),
            ],
        ),
        migrations.CreateModel(
            name='MemberReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42)),
                ('reputation', models.IntegerField(default=0)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.community')),
            ],
            options={
                'unique_together': {('community', 'address')},
            },
        ),
    ]
