# Generated by Django 6.1 on 2026-08-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_is_flagged_post_is_flagged'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('address', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('last_flag_time', models.IntegerField(default=0)),
            ],
        ),
    ]
