# Generated by Django 6.1 on 2026-08-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_useractivity_remove_comment_is_flagged_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_flagged',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_flagged',
        ),
    ]
