# Generated by Django 6.1 on 2026-08-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_comment_is_flagged_remove_post_is_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='reputation_reward_good_flag',
            field=models.IntegerField(default=2),
        ),
    ]
