# Generated by Django 6.1 on 2026-08-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_community_reputation_reward_good_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(max_length=42)),
                ('notification_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('link', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='successful_flagger',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='successful_flagger',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
