# Generated by Django 6.1 on 2026-08-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_notification_comment_successful_flagger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberreputation',
            name='last_flag_time',
            field=models.IntegerField(default=0),
        ),
    ]
