# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0007_memberreputation_last_flag_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="min_flag_age_seconds",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncstate",
            name="contract_address",
            field=models.CharField(blank=True, default="", max_length=42),
        ),
    ]
